language: rust
sude: required
dist: xenial
addons:
  apt:
    packages:
      - libssl-dev
os:
  - linux
rust:
  - stable
  - beta
cache: cargo
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then cargo install cargo-tarpaulin; fi
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
